server:
  port: 8081
spring:
  application:
    name: demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.94.163.232:3306/sign_detail?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: "root"
      initial-size: 5
      max-active: 10
      min-idle: 3
      filters: stat,wall
  security:
    user:
      password: root
      name: root
      roles: admin

mconfig:
  swagger-ui-open:true
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl